#--- New Jersey Municipalities ---#
Bergen_Muni_List = ['Allendale ', 'Harrington Park ', 'Ramsey ', 'Alpine ', 'Hasbrouck Heights ', 'Ridgefield ', 'Bergenfield ', 'Haworth ', 'Ridgefield Park ', 'Bogota ', 'Hillsdale ', 'Ridgewood ', 'Carlstadt ', 'Ho Ho Kus ', 'River Edge ', 'Cliffside Park ', 'Leonia ', 'River Vale ', 'Closter ', 'Little Ferry ', 'Rochelle Park ', 'Cresskill ', 'Lodi ', 'Rockleigh ', 'Demarest ', 'Lyndhurst ', 'Rutherford ', 'Dumont ', 'Mahwah ', 'Saddle Brook ', 'East Rutherford ', 'Maywood ', 'Saddle River ', 'Edgewater ', 'Midland Park ', 'South Hackensack ', 'Elmwood Park ', 'Montvale ', 'Teaneck ', 'Emerson ', 'Moonachie ', 'Tenafly ', 'Englewood ', 'New Milford ', 'Teterboro ', 'Englewood Cliffs ', 'North Arlington ', 'Upper Saddle River ', 'Fair Lawn ', 'Northvale ', 'Waldwick ', 'Fairview ', 'Norwood ', 'Wallington ', 'Fort Lee ', 'Oakland ', 'Washington Township ', 'Franklin Lakes ', 'Old Tappan ', 'Westwood ', 'Garfield ', 'Oradell ', 'Woodcliff Lake ', 'Glen Rock ', 'Palisades Park', 'Wood-Ridge ', 'Hackensack ', 'Paramus ', 'Wyckoff ', 'Park Ridge ']
Salem_Muni_List = ['Alloway Township', 'Carneys Point Township', 'Elmer', 'Elsinboro Township', 'Lower Alloways Creek Township', 'Mannington Township', 'Oldmans Township', 'Penns Grove', 'Pennsville Township', 'Pilesgrove Township', 'Pittsgrove Township', 'Quinton Township', 'Salem', 'Upper Pittsgrove Township', 'Woodstown']
Sussex_Muni_List = ['Walpack Township', 'Andover', 'Branchville', 'Sandyston Township', 'Sussex', 'Ogdensburg', 'Lafayette Township', 'Hamburg', 'Fredon Township', 'Green Township', 'Stanhope', 'Montague Township', 'Stillwater Township', 'Franklin', 'Hampton Township', 'Frankford Township', 'Andover Township', 'Newton', 'Hardyston Township', 'Byram Township', 'Wantage Township', 'Hopatcong', 'Sparta Township']
Hunterdon_Muni_List = ['Stockton', 'Bloomsbury', 'Califon', 'Milford', 'Lebanon', 'Frenchtown', 'Hampton', 'Glen Gardner', 'Clinton (town)' ,'West Amwell Township', 'Franklin Township', 'High Bridge', 'Kingwood Township', 'Lambertville', 'Bethlehem Township', 'East Amwell Township', 'Delaware Township', 'Flemington', 'Alexandria Township', 'Holland Township', 'Union Township', 'Tewksbury Township', 'Lebanon Township', 'Clinton Township', 'Readington Township', 'Raritan Township']
Warren_Muni_List = ["Allamuchy Township", "Alpha", "Belvidere", "Blairstown Township", "Franklin Township", "Frelinghuysen Township", "Greenwich Township", "Hackettstown", "Hardwick Township", "Harmony Township", "Hope Township", "Independence Township", "Knowlton Township", "Liberty Township", "Lopatcong Township", "Mansfield Township", "Oxford Township", "Phillipsburg" , "Pohatcong Township", "Washington Borough", "Washington Township", "White Township"]
Cumberland_Muni_List = ['Bridgeton', 'Commercial Township', 'Deerfield Township', 'Downe Township', 'Fairfield Township', 'Greenwich Township', 'Hopewell Township', 'Lawrence Township', 'Maurice River Township', 'Millville', 'Shiloh', 'Stow Creek Township', 'Upper Deerfield Township', 'Vineland']
Cape_May_Muni_List = ["Cape May Point", "West Wildwood", "Stone Harbor", "West Cape May", "Avalon", "Sea Isle City", "Woodbine", "Wildwood Crest", "Cape May", "North Wildwood", "Wildwood", "Dennis Township", "Ocean City", "Upper Township", "Middle Township", "Lower Township"]
Atlantic_Muni_List = ['Corbin City', 'Longport', 'Port Republic', 'Estell Manor', 'Folsom', 'Weymouth Township', 'Egg Harbor City', 'Buena', 'Mullica Township', 'Margate City', 'Linwood', 'Buena Vista Township', 'Absecon', 'Northfield', 'Brigantine', 'Ventnor City', 'Somers Point', 'Hammonton', 'Pleasantville', 'Hamilton Township', 'Galloway Township', 'Atlantic City', 'Egg Harbor Township']
Burlington_Muni_List = ["Fieldsboro", "Washington Township", "Wrightstown", "Pemberton", "Bass River Township", "Woodland Township", "Beverly", "Riverton", "Springfield Township", "Bordentown", "Medford Lakes", "Delanco Township", "Eastampton Township", "Hainesport Township", "Shamong Township", "Tabernacle Township", "New Hanover Township", "Palmyra", "North Hanover Township", "Chesterfield Township", "Riverside Township", "Mansfield Township", "Westampton Township", "Edgewater Park", "Mount Holly", "Burlington", "Southampton Township", "Bordentown Township", "Florence Township", "Lumberton Township", "Cinnaminson Township", "Delran Township", "Maple Shade Township", "Moorestown Township", "Burlington Township", "Medford", "Pemberton Township", "Willingboro Township", "Mount Laurel", "Evesham Township"]
Gloucester_Muni_List = ["Newfield", "Wenonah", "Swedesboro", "National Park", "Woodbury Heights", "South Harrison Township", "Elk Township", "Westville", "Greenwich Township", "Logan Township", "Paulsboro", "Clayton", "Pitman", "East Greenwich Township", "Woodbury", "Woolwich Township", "Harrison Township", "Mantua Township", "Franklin Township", "Glassboro", "West Deptford Township", "Deptford Township", "Monroe Township", "Washington Township"]

#-- New York Municipalities --#
Putnam_Muni_List = ["Carmel", "Kent", "Patterson", "Philipstown", "Putnam Valley", "Southeast", "Brewster", "Cold Spring", "Nelsonville", "Brewster Heights", "Brewster Hill", "Carmel", "Lake Carmel", "Mahopac", "Peach Lake", "Putnam Lake", "Farmers Mills", "Garrison", "Gayville", "Lake Peekskill", "Ludingtonville", "Sodom", "Tompkins Corners", "Doanesburgh", "Dicktown"]

#--  --#
raw_Countylists = globals() 
